#theme = "darcula"
#theme = "darcula-solid"
theme = "github_dark"
#theme = "gruvbox"
#theme = "gruvbox_dark_hard"
#theme = "hex_steel"
#theme = "jellybeans"

[editor]
scrolloff = 10
line-number = "absolute"
cursorline = true
#cursorcolumn = true


[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["diagnostics"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
